### PR TITLE
keep fork up to date

### PR DESCRIPTION
**Pull request by Shluffy**
there were conflicts, so doing it this way

### CODE REVIEW

**Comment by Shluffy** [comment]
@ZI-Youtuber can I pls have write access to resolve conflicts

**Comment by ZI-Youtuber** [comment]
@Shluffy ok will do

**Review by ZI-Youtuber — CHANGES_REQUESTED** [review]
Can you delte the README.md file pls

**Comment by Shluffy** [comment]
> Can you delte the README.md file pls

did that, but it still says conflicting. I'm on a chromebook so I can't run the command line as far as i know

**Comment by Shluffy** [comment]
@ZI-Youtuber we need to keep readme.md the same without changing it. I am going to reopen this in a new pr and see if that works. if not, I will manually add their readme.md

**Pull request closed without merging**
