### PR TITLE
Keep fork up to date

### PR DESCRIPTION
**Pull request by Shluffy**
Shouldn't contradict

### CODE REVIEW

**Comment by Shluffy** [comment]
@ZI-Youtuber

**Comment by ZI-Youtuber** [comment]
@Shluffy Will do

**Review by ZI-Youtuber — APPROVED** [review]

**Review by ZI-Youtuber — APPROVED** [review]

**Review by ZI-Youtuber — APPROVED** [review]

**Comment by Shluffy** [comment]
And the readme.md?

**Comment by ZI-Youtuber** [comment]
@Shluffy  I'm unable to merge this pull request because of it having conflicts with the branch so you might have to change that

**Comment by Shluffy** [comment]
> @Shluffy I'm unable to merge this pull request because of it having conflicts with the branch so you might have to change that

I'll look into the readme.md problem

**Comment by ZI-Youtuber** [comment]
> > @Shluffy I'm unable to merge this pull request because of it having conflicts with the branch so you might have to change that
> 
> I'll look into the readme.md problem

ok

**Review by ZI-Youtuber — APPROVED** [review]

**Comment by Shluffy** [comment]
Merging #3 should allow us to merge this.

**Comment by Shluffy** [comment]
Closed?

**Comment by Shluffy** [comment]
and if you reopen this it sjouldn;t contradict

**Pull request closed without merging**
